package com.axa.dm.helper.helper;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Helper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cover Period in Year")
	private java.lang.String coverPeriodInYear;
	@org.kie.api.definition.type.Label("No of Domestic Helper")
	private java.lang.String noOfHelper;
	@org.kie.api.definition.type.Label("Helper Promotion Code")
	private java.lang.String helperPromotionCode;
	@org.kie.api.definition.type.Label("Premium Amount")
	private java.lang.String premiumAmount;
	@org.kie.api.definition.type.Label("Levy Amount")
	private java.lang.String levyAmount;
	@org.kie.api.definition.type.Label("Discount Amount")
	private java.lang.String discountAmount;
	@org.kie.api.definition.type.Label("Total Premium Amount")
	private java.lang.String totalPremiumAmount;

	@org.kie.api.definition.type.Label("Helper Details")
	private java.util.List<com.axa.dm.helper.helper.HelperDetails> helperDetails;

	@org.kie.api.definition.type.Label(value = "Levy")
	private java.math.BigDecimal levy;

	@org.kie.api.definition.type.Label(value = "Premium")
	private java.math.BigDecimal premium;

	@org.kie.api.definition.type.Label(value = "Total Premium")
	private java.math.BigDecimal totalPremium;

	public Helper() {
	}

	public java.lang.String getCoverPeriodInYear() {
		return this.coverPeriodInYear;
	}

	public void setCoverPeriodInYear(java.lang.String coverPeriodInYear) {
		this.coverPeriodInYear = coverPeriodInYear;
	}

	public java.lang.String getNoOfHelper() {
		return this.noOfHelper;
	}

	public void setNoOfHelper(java.lang.String noOfHelper) {
		this.noOfHelper = noOfHelper;
	}

	public java.lang.String getHelperPromotionCode() {
		return this.helperPromotionCode;
	}

	public void setHelperPromotionCode(java.lang.String helperPromotionCode) {
		this.helperPromotionCode = helperPromotionCode;
	}

	public java.lang.String getPremiumAmount() {
		return this.premiumAmount;
	}

	public void setPremiumAmount(java.lang.String premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public java.lang.String getLevyAmount() {
		return this.levyAmount;
	}

	public void setLevyAmount(java.lang.String levyAmount) {
		this.levyAmount = levyAmount;
	}

	public java.lang.String getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(java.lang.String discountAmount) {
		this.discountAmount = discountAmount;
	}

	public java.lang.String getTotalPremiumAmount() {
		return this.totalPremiumAmount;
	}

	public void setTotalPremiumAmount(java.lang.String totalPremiumAmount) {
		this.totalPremiumAmount = totalPremiumAmount;
	}

	public java.util.List<com.axa.dm.helper.helper.HelperDetails> getHelperDetails() {
		return this.helperDetails;
	}

	public void setHelperDetails(
			java.util.List<com.axa.dm.helper.helper.HelperDetails> helperDetails) {
		this.helperDetails = helperDetails;
	}

	public java.math.BigDecimal getLevy() {
		return this.levy;
	}

	public void setLevy(java.math.BigDecimal levy) {
		this.levy = levy;
	}

	public java.math.BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(java.math.BigDecimal premium) {
		this.premium = premium;
	}

	public java.math.BigDecimal getTotalPremium() {
		return this.totalPremium;
	}

	public void setTotalPremium(java.math.BigDecimal totalPremium) {
		this.totalPremium = totalPremium;
	}

	public Helper(
			java.lang.String coverPeriodInYear,
			java.lang.String noOfHelper,
			java.lang.String helperPromotionCode,
			java.lang.String premiumAmount,
			java.lang.String levyAmount,
			java.lang.String discountAmount,
			java.lang.String totalPremiumAmount,
			java.util.List<com.axa.dm.helper.helper.HelperDetails> helperDetails,
			java.math.BigDecimal levy, java.math.BigDecimal premium,
			java.math.BigDecimal totalPremium) {
		this.coverPeriodInYear = coverPeriodInYear;
		this.noOfHelper = noOfHelper;
		this.helperPromotionCode = helperPromotionCode;
		this.premiumAmount = premiumAmount;
		this.levyAmount = levyAmount;
		this.discountAmount = discountAmount;
		this.totalPremiumAmount = totalPremiumAmount;
		this.helperDetails = helperDetails;
		this.levy = levy;
		this.premium = premium;
		this.totalPremium = totalPremium;
	}

}