package com.axa.dm.helper.helper;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Helper")
	private com.axa.dm.helper.helper.Helper helper;

	public ProcessObject() {
	}

	public com.axa.dm.helper.helper.Helper getHelper() {
		return this.helper;
	}

	public void setHelper(com.axa.dm.helper.helper.Helper helper) {
		this.helper = helper;
	}

	public ProcessObject(com.axa.dm.helper.helper.Helper helper) {
		this.helper = helper;
	}

}