package com.axa.dm.travel;

import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Travel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Travel Plan")
	private java.lang.String travelPlan;
	@org.kie.api.definition.type.Label("Travel Cover")
	private java.lang.String travelCover;
	@org.kie.api.definition.type.Label("Travel Type")
	private java.lang.String travelType;
	@org.kie.api.definition.type.Label("Travel Start Date")
	private java.lang.String travelStartDate;
	@org.kie.api.definition.type.Label("Travel End Date")
	private java.lang.String travelEndDate;
	@org.kie.api.definition.type.Label("Travel Enhance Personal Accident Benefit Flag")
	private java.lang.String travelEnhanceFlag;
	@org.kie.api.definition.type.Label("Travel Enhance Children Cover Flag")
	private java.lang.String travelEnhanceChildFlag;
	@org.kie.api.definition.type.Label("Travel No Of Insured Person For China Hospital Card")
	private java.lang.String travelNoOfPersonWithCard;
	@org.kie.api.definition.type.Label("Travel Promotion Code")
	private java.lang.String travelPromotionCode;

	@org.kie.api.definition.type.Label("Travel Premium Amount")
	private java.lang.String travelPremiumAmount;

	@org.kie.api.definition.type.Label("Travel Levy Amount")
	private java.lang.String travelLevyAmount;

	@org.kie.api.definition.type.Label("Travel Discount Amount")
	private java.lang.String travelDiscountAmount;

	@org.kie.api.definition.type.Label("Travel Total Premium Amount")
	private java.lang.String travelTotalPremiumAmount;

	private String dateFormatStr = "yyyyMMdd";

	@org.kie.api.definition.type.Label("Additional Premium")
	private java.math.BigDecimal additionalPremium;

	@org.kie.api.definition.type.Label("Premium Amount")
	private java.math.BigDecimal premiumAmount;

	@org.kie.api.definition.type.Label("Levy Amount")
	private java.math.BigDecimal levyAmount;

	@org.kie.api.definition.type.Label("Discount Amount")
	private java.math.BigDecimal discountAmount;

	@org.kie.api.definition.type.Label("Max Days before additional days")
	private java.lang.String maxDays;

	@org.kie.api.definition.type.Label("Discount")
	private java.math.BigDecimal discount;

	@org.kie.api.definition.type.Label("Levy")
	private java.math.BigDecimal levy;

	@org.kie.api.definition.type.Label("Total Premium Amount")
	private java.math.BigDecimal totalPremiumAmount;

	@org.kie.api.definition.type.Label(value = "Amount per person")
	private java.math.BigDecimal amtPerPerson;

	public Travel() {
	}

	public java.lang.String getTravelPlan() {
		return this.travelPlan;
	}

	public void setTravelPlan(java.lang.String travelPlan) {
		this.travelPlan = travelPlan;
	}

	public java.lang.String getTravelCover() {
		return this.travelCover;
	}

	public void setTravelCover(java.lang.String travelCover) {
		this.travelCover = travelCover;
	}

	public java.lang.String getTravelType() {
		return this.travelType;
	}

	public void setTravelType(java.lang.String travelType) {
		this.travelType = travelType;
	}

	public java.lang.String getTravelStartDate() {
		return this.travelStartDate;
	}

	public void setTravelStartDate(java.lang.String travelStartDate) {
		this.travelStartDate = travelStartDate;
	}

	public java.lang.String getTravelEndDate() {
		return this.travelEndDate;
	}

	public void setTravelEndDate(java.lang.String travelEndDate) {
		this.travelEndDate = travelEndDate;
	}

	public java.lang.String getTravelEnhanceFlag() {
		return this.travelEnhanceFlag;
	}

	public void setTravelEnhanceFlag(java.lang.String travelEnhanceFlag) {
		this.travelEnhanceFlag = travelEnhanceFlag;
	}

	public java.lang.String getTravelEnhanceChildFlag() {
		return this.travelEnhanceChildFlag;
	}

	public void setTravelEnhanceChildFlag(
			java.lang.String travelEnhanceChildFlag) {
		this.travelEnhanceChildFlag = travelEnhanceChildFlag;
	}

	public java.lang.String getTravelNoOfPersonWithCard() {
		return this.travelNoOfPersonWithCard;
	}

	public void setTravelNoOfPersonWithCard(
			java.lang.String travelNoOfPersonWithCard) {
		this.travelNoOfPersonWithCard = travelNoOfPersonWithCard;
	}

	public java.lang.String getTravelPromotionCode() {
		return this.travelPromotionCode;
	}

	public void setTravelPromotionCode(java.lang.String travelPromotionCode) {
		this.travelPromotionCode = travelPromotionCode;
	}

	public java.lang.String getTravelPremiumAmount() {
		return this.travelPremiumAmount;
	}

	public void setTravelPremiumAmount(java.lang.String travelPremiumAmount) {
		this.travelPremiumAmount = travelPremiumAmount;
	}

	public java.lang.String getTravelLevyAmount() {
		return this.travelLevyAmount;
	}

	public void setTravelLevyAmount(java.lang.String travelLevyAmount) {
		this.travelLevyAmount = travelLevyAmount;
	}

	public java.lang.String getTravelDiscountAmount() {
		return this.travelDiscountAmount;
	}

	public void setTravelDiscountAmount(java.lang.String travelDiscountAmount) {
		this.travelDiscountAmount = travelDiscountAmount;
	}

	public java.lang.String getTravelTotalPremiumAmount() {
		return this.travelTotalPremiumAmount;
	}

	public void setTravelTotalPremiumAmount(
			java.lang.String travelTotalPremiumAmount) {
		this.travelTotalPremiumAmount = travelTotalPremiumAmount;
	}

	public java.lang.Integer getNoOfDays() {
		Integer i = null;
		if (this.getTravelEndDateCal() != null
				&& this.getTravelStartDateCal() != null) {
			long startTime = this.getTravelStartDateCal().getTime();
			long endTime = this.getTravelEndDateCal().getTime();
			long diffTime = endTime - startTime;
			long diffDays = diffTime / (1000 * 60 * 60 * 24);
			i = (int) diffDays + 1;
		}
		return i;
	}

	public java.util.Date getTravelEndDateCal() {
		try {

			if (this.travelEndDate != null && !this.travelEndDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat(dateFormatStr)
						.parse(this.travelEndDate);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public java.util.Date getTravelStartDateCal() {
		try {

			if (this.travelStartDate != null && !this.travelStartDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat(dateFormatStr)
						.parse(this.travelStartDate);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public Travel(java.lang.String travelPlan, java.lang.String travelCover,
			java.lang.String travelType, java.lang.String travelStartDate,
			java.lang.String travelEndDate, java.lang.String travelEnhanceFlag,
			java.lang.String travelEnhanceChildFlag,
			java.lang.String travelNoOfPersonWithCard,
			java.lang.String travelPromotionCode,
			java.lang.String travelPremiumAmount,
			java.lang.String travelLevyAmount,
			java.lang.String travelDiscountAmount,
			java.lang.String travelTotalPremiumAmount) {
		this.travelPlan = travelPlan;
		this.travelCover = travelCover;
		this.travelType = travelType;
		this.travelStartDate = travelStartDate;
		this.travelEndDate = travelEndDate;
		this.travelEnhanceFlag = travelEnhanceFlag;
		this.travelEnhanceChildFlag = travelEnhanceChildFlag;
		this.travelNoOfPersonWithCard = travelNoOfPersonWithCard;
		this.travelPromotionCode = travelPromotionCode;
		this.travelPremiumAmount = travelPremiumAmount;
		this.travelLevyAmount = travelLevyAmount;
		this.travelDiscountAmount = travelDiscountAmount;
		this.travelTotalPremiumAmount = travelTotalPremiumAmount;
	}

	public java.math.BigDecimal getAdditionalPremium() {
		return this.additionalPremium;
	}

	public void setAdditionalPremium(java.math.BigDecimal additionalPremium) {
		this.additionalPremium = additionalPremium;
	}

	public java.math.BigDecimal getPremiumAmount() {
		return this.premiumAmount;
	}

	public void setPremiumAmount(java.math.BigDecimal premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public java.math.BigDecimal getLevyAmount() {
		return this.levyAmount;
	}

	public void setLevyAmount(java.math.BigDecimal levyAmount) {
		this.levyAmount = levyAmount;
	}

	public java.math.BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	public java.lang.String getMaxDays() {
		return this.maxDays;
	}

	public void setMaxDays(java.lang.String maxDays) {
		this.maxDays = maxDays;
	}

	public java.math.BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.math.BigDecimal discount) {
		this.discount = discount;
	}

	public java.math.BigDecimal getLevy() {
		return this.levy;
	}

	public void setLevy(java.math.BigDecimal levy) {
		this.levy = levy;
	}

	public java.math.BigDecimal getTotalPremiumAmount() {
		return this.totalPremiumAmount;
	}

	public void setTotalPremiumAmount(java.math.BigDecimal totalPremiumAmount) {
		this.totalPremiumAmount = totalPremiumAmount;
	}

	public java.math.BigDecimal getAmtPerPerson() {
		return this.amtPerPerson;
	}

	public void setAmtPerPerson(java.math.BigDecimal amtPerPerson) {
		this.amtPerPerson = amtPerPerson;
	}

	public Travel(java.lang.String travelPlan, java.lang.String travelCover,
			java.lang.String travelType, java.lang.String travelStartDate,
			java.lang.String travelEndDate, java.lang.String travelEnhanceFlag,
			java.lang.String travelEnhanceChildFlag,
			java.lang.String travelNoOfPersonWithCard,
			java.lang.String travelPromotionCode,
			java.lang.String travelPremiumAmount,
			java.lang.String travelLevyAmount,
			java.lang.String travelDiscountAmount,
			java.lang.String travelTotalPremiumAmount,
			java.lang.String dateFormatStr,
			java.math.BigDecimal additionalPremium,
			java.math.BigDecimal premiumAmount,
			java.math.BigDecimal levyAmount,
			java.math.BigDecimal discountAmount, java.lang.String maxDays,
			java.math.BigDecimal discount, java.math.BigDecimal levy,
			java.math.BigDecimal totalPremiumAmount,
			java.math.BigDecimal amtPerPerson) {
		this.travelPlan = travelPlan;
		this.travelCover = travelCover;
		this.travelType = travelType;
		this.travelStartDate = travelStartDate;
		this.travelEndDate = travelEndDate;
		this.travelEnhanceFlag = travelEnhanceFlag;
		this.travelEnhanceChildFlag = travelEnhanceChildFlag;
		this.travelNoOfPersonWithCard = travelNoOfPersonWithCard;
		this.travelPromotionCode = travelPromotionCode;
		this.travelPremiumAmount = travelPremiumAmount;
		this.travelLevyAmount = travelLevyAmount;
		this.travelDiscountAmount = travelDiscountAmount;
		this.travelTotalPremiumAmount = travelTotalPremiumAmount;
		this.dateFormatStr = dateFormatStr;
		this.additionalPremium = additionalPremium;
		this.premiumAmount = premiumAmount;
		this.levyAmount = levyAmount;
		this.discountAmount = discountAmount;
		this.maxDays = maxDays;
		this.discount = discount;
		this.levy = levy;
		this.totalPremiumAmount = totalPremiumAmount;
		this.amtPerPerson = amtPerPerson;
	}

}